language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
env:
  global:
    ENV=TRAVIS
sudo: false     
before_script:
  - npm install -g codecov 
script:
  - npm run test
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov 
