language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
services:
    - postgresql
env:
  global:
    ENV=TRAVIS
sudo: false
install:
  - npm install -g codecov    
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm run test
after_success:
 - nyc report --reporter=text-lcov > coverage.lcov && codecov
